### ISSUE TITLE
Installation failed: k is not defined.

### ISSUE THREAD

**Issue by geoidesic** [WBHarry/join-combat#1]

**Comment by WBHarry** [comment]
A lot of these errors going around now with Foundry v10 coming up!

It should be fixed now with the latest update I did. :grin:

**Comment by geoidesic** [comment]
Hmm.. still not. Maybe you didn't update Foundry's manifest record? It still shows there as v1.0.0

**Comment by WBHarry** [comment]
Alright, soooo..here's the deal. I have a few other modules that I've been updating to v10. I didn't actually properly look at which one this issue belonged to, so I fixed the same issue in a different module 😆 

It should be all good to go now.
